# Generated by Django 3.2.6 on 2021-08-12 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=32)),
                ('dept_intake', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rn', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=32)),
                ('marks', models.FloatField()),
                ('dept', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CollegeApp.dept')),
            ],
        ),
        migrations.CreateModel(
            name='Prof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('salary', models.FloatField()),
                ('dept', models.ManyToManyField(to='CollegeApp.Dept')),
            ],
        ),
    ]
