# Generated by Django 3.2.6 on 2021-08-12 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CollegeApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dept',
            old_name='dept_intake',
            new_name='intake',
        ),
        migrations.RenameField(
            model_name='dept',
            old_name='dept_name',
            new_name='name',
        ),
    ]
