# Generated by Django 3.2.6 on 2021-08-12 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CollegeApp', '0002_auto_20210812_1016'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prof',
        ),
    ]
