# Generated by Django 3.2.6 on 2021-08-12 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CollegeApp', '0003_delete_prof'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
