# Generated by Django 3.2.6 on 2021-08-12 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CollegeApp', '0004_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rn', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=32)),
                ('marks', models.FloatField()),
                ('dept', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CollegeApp.dept')),
            ],
        ),
    ]
